### ISSUE TITLE
Conky Menu has some issues.

### ISSUE THREAD

**Issue by sdjrdriver** [km4ack/73Linux#1]
Fresh install of 73 Linux, looks like some issues with Letter sizes and text formatting

![image](https://user-images.githubusercontent.com/28915155/203660606-34cc2fd3-d9da-4991-8758-5be1e74990a8.png)

Not 100% sure where to adjust these settings to fix this and make it cleaner.

**Comment by km4ack** [comment]
I reduced the max width so Conky didn't take up as much screen real estate so I am guessing that is the issue. Edit your conkyrc file by running `nano ~/.conkyrc`. Look for this line close to the top of the file **maximum_width = 400,** and try adding ~50 to what you currently have and see if that clears it up.

**Comment by sdjrdriver** [comment]
Sadly it did not, what is the recommended method of restarting conky? I noticed when i kill -9 the process and restart it, it looks funky

**Comment by sdjrdriver** [comment]
Ok so I isolated the overwriting issues I was seeing. This was due to the usage of

`own_window_transparent = true`
I set it to false, and no longer does the wierd overwrite stuff.

I have to play with the size issue a bit more but I have done a few mods that seem to work ok for now but I will make it bigger later

`conky.config = {
	background = true,
	use_xft = true,
	font = '123:size=8',
	xftalpha = 0.5,
	update_interval = 0.5,
	total_run_times = 0,
	own_window = true,
	own_window_type = 'normal',
	own_window_transparent = false,
	own_window_hints = 'undecorated,below,sticky,skip_taskbar,skip_pager',
	double_buffer = true,
	minimum_width = 250, minimum_height = 40,
	maximum_width = 450,
	draw_shades = false,
	draw_outline = false,
	draw_borders = false,
	draw_graph_borders = false,
	default_color = 'gray',
	default_shade_color = 'red',
	default_outline_color = 'green',
	alignment = 'top_right',
	gap_x = 10,
	gap_y = 10,
	no_buffers = true,
	uppercase = false,
	cpu_avg_samples = 2,
	net_avg_samples = 1,
	override_utf8_locale = true,
	use_spacer = 'right',
};

conky.text = [[

${voffset -20}
${font Arial:size=30}${color Yellow}${alignc}K5CDW
${voffset -45}
#${font Arial:bold:size=14}${color White}Gridsquare ${alignr}${color Yellow}${execi 60 cat /run/user/1000/gridinfo.txt | cut -c1-8}
#${font Arial:bold:size=14}${color White}Radio Freq ${alignr}${color Yellow}${execi 5 $HOME/bin/conky/get-freq | cut -c1-6}
#${font Arial:bold:size=14}${color White}Radio Freq A ${if_match "VFOA" == "${execi 5 $HOME/bin/conky/get-vfo}"}*$endif\
#${alignr}${color Yellow}${execi 5 $HOME/bin/conky/get-freq VFOA | cut -c1-7}
#${font Arial:bold:size=14}${color White}Radio Freq B ${if_match "VFOB" == "${execi 5 $HOME/bin/conky/get-vfo}"}*$endif\
#${alignr}${color Yellow}${execi 5 $HOME/bin/conky/get-freq VFOB | cut -c1-7}
${font Arial:bold:size=14}${color Yellow}LOCAL${alignr}ZULU
${voffset -30}
${color DarkSlateGray}${hr 2}
${voffset -35}
${font Arial:size=20}${color White}${time %H:%M:%S}\
${alignr}${tztime Zulu %H:%M:%S}
${font Arial:size=20}${color White}${time %d%b%y}\
${alignr}${tztime Zulu %d%b%y}


${voffset -200}


${color grey}
${font}
${font Arial:size=12}${color Yellow}SYSTEM ${color DarkSlateGray} ${hr 2}
${font Arial:size=12}${color White}Frequency $alignr${freq_g cpu0}Ghz
${font Arial:size=12}${color White}Uptime $alignr${uptime}
#TEMP
${voffset -15}
${font Arial:size=8}${color White}CPU${alignr}${cpu}%
${cpubar cpu}
${font Arial:size=8}${color White}MEM $alignc $mem / $memmax $alignr $memperc%
$membar
${font Arial:size=8}${color White}SWAP $alignc $swap / $swapmax $alignr $swapperc%
$swapbar
${font Arial:size=8}${color White}HDD $alignc ${fs_used /home} / ${fs_size /home} $alignr ${fs_free_perc /home}%
${fs_bar /home}

${font Arial:size=12}${color Yellow}NETWORK ${color DarkSlateGray}${hr 2}
${font Arial:size=12}${color White}Wireless IP $alignr ${addr wlp5s0}

${font Arial:size=12}${color Yellow}RADIO TOOLS ${color DarkSlateGray}${hr 2}
${font Arial:size=10}${if_running ardopc64}${color green}ARDOP ACTIVE${else}${color red}ARDOP OFF$endif \
${alignr}${if_running rigctld}${color green}RIGCTL ACTIVE${else}${color red}RIGCTL OFF$endif
${if_running kissattach}${color green}KISSATCH ACTIVE${else}${color red}KISSATCH OFF$endif \
${alignr}${if_running direwolf}${color green}DIREWOLF ACTIVE${else}${color red}DIREWOLF OFF$endif

${font Arial:size=12}${color Yellow}DIGITAL APPS ${color DarkSlateGray}${hr 2}
${font Arial:size=10}${if_running js8call}${color green}JS8 ACTIVE${else}${color red}JS8 OFF$endif \
${alignr}${if_running flrig}${color green}FLRIG ACTIVE${else}${color red}FLRIG OFF$endif
${if_running garim}${color green}GARIM ACTIVE${else}${color red}GARIM OFF$endif \
${alignr}${if_running fldigi}${color green}FLDIGI ACTIVE${else}${color red}FLDIGI OFF$endif
${if_running pavucontrol}${color green}PULSE ACTIVE${else}${color red}PULSE OFF$endif \
${alignr}${if_running pat}${color green}PAT ACTIVE${else}${color red}PAT OFF$endif

${font Arial:size=12}${color Yellow}RECENT LOG ENTRIES ${color DarkSlateGray}${hr 2}
${font Arial:size=10}${color White}${tail ~/Documents/mylog.txt 5}



#$diskio
]];
`

**Comment by km4ack** [comment]
Thanks for the update. Which OS are you using and what is the screen resolution?

**Comment by sdjrdriver** [comment]
Hey there sorry about that, makes sense that this would be helpful info!

k5cdw@wraithbox-linux:~$ cat /etc/lsb-release 
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=22.04
DISTRIB_CODENAME=jammy
DISTRIB_DESCRIPTION="Ubuntu 22.04.1 LTS"

![image](https://user-images.githubusercontent.com/28915155/203675399-862ca9ea-2e87-4c3b-b662-0bb544ee689b.png)

Dual monitor 1920x1080 in 16:9 config
