### ISSUE TITLE
Fldigi under Wayland causes crippling CPU-usage (RPi 8gb)

### ISSUE THREAD

**Issue by NullVibes** [km4ack/73Linux#102]
On a RPi-8g, Fldigi under Wayland causes CPU-usage to spike significantly, and makes the RPi unusable.  To troubleshoot, Conky cron job was #'d and the process killed manually, AND SwapFile was increased from 100M to 1GB, with no effect.  A quick Google search mentions this as a known CPU issue and not memory.

The resolution was to use the Xorg window manager, and not Wayland.  Use `sudo raspi-config`, option A6, to revert back to Xorg.  Under X, fldigi works great, even if you configure an absurdly large waterfall size (like I do.)

**Comment by km4ack** [comment]
closing issue and leaving documentation label so it can be referenced as needed.
