### ISSUE TITLE
Fldigi Suite on Mint 22 needs libfltk1.3-dev, libsndfile1-dev and portaudio19-dev

### ISSUE THREAD

**Issue by lysack** [km4ack/73Linux#103]
On Mint 22:

1. Fldigi Suite requires libfltk1.3-dev
2. Fldigi requires libsndfile1-dev (plus it's depencies) and portaudio19-dev

**Comment by NullVibes** [comment]
Issue resolved?  Just tested on Mint 22 and had no issues.  Recommend closing ticket.

**Comment by km4ack** [comment]
Thanks for the heads up @NullVibes
