### ISSUE TITLE
deprecate hotspot tools

### ISSUE THREAD

**Issue by km4ack** [km4ack/73Linux#107]
With the addition of the wifi hotspot built into Bookworm, there's no need for HotSpot Tools at this point.

**Comment by jbird4h30** [comment]
How does it work now, though? It appears that if I remove ethernet, and disconnect from my shack wifi: my Pi 4 doesn't revert to broadcasting its own hotspot network like it used to with Build-a-Pi. So then I can't connect to it anymore with VNC in the field.
