### ISSUE TITLE
Linux Mint 22 Ardop Install ardopc64 file missing

### ISSUE THREAD

**Issue by n1rog** [km4ack/73Linux#114]
After a fresh install of Mint 22 & 73Linux (including Pat Menu), when attempting to launch the Ardop modem I receive the following error.

------------------------------------------------------------------
 There was an error creating the child process for this terminal
 
Failed to execute child process “/usr/local/bin/ardopc64”: Failed to execve: No such file or directory

------------------------------------------------------------------

I have verified that the "ardopc64" file does not exist. However, the "ardopcf" file does.

Any guidance would be appreciated.
Roger

**Comment by km4ack** [comment]
In Pat Menu Setting->Current Config change the ARDOP command to point to the correct file (ardopcf). You can also add any other options you need in this line.

**Comment by km4ack** [comment]
Verify pat is running in the background and double check the port configured in the pat conf file (not pat menu). If it's different than 8080, change the port number in pat menu settings to match what is in the pat config file.

Also, check out https://groups.io/g/KM4ACK-Pi/topics where issues like this have been covered in the past.

**Comment by ke5di** [comment]
I know this is closed, but I've modified the stop modems script in my local to add ardopcf to the kill list...
