### ISSUE TITLE
Nothing selected to install. Exiting

### ISSUE THREAD

**Issue by Devin82m** [km4ack/73Linux#116]
Hello, I run the script, give it my callsign, check the boxes next to the items I want (all of them), and click Built It. But it exists to the "Nothing selected to install. Exiting" error. I've tried it twice, making sure everything is selected and I am in fact clicking Built It. I tried not selecting anything and got the same error. Is there a way to run this without the gui? I want to install everything. I'm a Seniro DevOps Engineer and can spend some time troubleshooting it, but thought I would share the issue here in case others have this issue. Please let me know if there is an easy work around. Thanks!

**Comment by Devin82m** [comment]
I would suggest adding a Install All or Select All button since many of us most likely want to install everything, not fully know what everything does.

**Comment by Devin82m** [comment]
I fixed it, the cache directory was owned by root, I chowned it to my user and it's working now.

**Comment by km4ack** [comment]
Just curious, which OS are you running?

**Comment by sv0sgs** [comment]
I have the same problem.  I am using Pi OS ("Bookworm") on a Pi 4B.  Fresh install, nothing added.

**Comment by sv0sgs** [comment]
> I fixed it, the cache directory was owned by root, I chowned it to my user and it's working now.

I have the same issue on a Pi4b running 32-bit "Bookworm." Where do I find the cache directory?

**Comment by km4ack** [comment]
The cache dir is inside the 73Linux dir that should be in your home dir.
