### ISSUE TITLE
Some applications will not install (Flrig, 

### ISSUE THREAD

**Issue by jon-coffee** [km4ack/73Linux#117]
Hello,

Freshly installed linux mint 22 cinnamon on my Evolve Maestro. 

can't figure out what i'm doing wrong. But throughout the install many applications fail to install (FLRIG, FLDIGI etc.)

#Check Version  FLDIGI 	
###################################
UPDATE: 4.2.06 is available and 0 is installed

Noticing a few consistent errors:

WARNING: apt does not have a stable CLI interface. Use with caution in scripts.

AND

configure: error: 
  *** The fltk-config script could not be found. Please install the development
checking for fltk-config... no
  *** headers and libraries for FLTK 1.1.x, or set PATH to the directory that
  *** contains fltk-config.
          
make: *** No targets specified and no makefile found.  Stop.
make: *** No rule to make target 'install'.  Stop.
make: *** No rule to make target 'clean'.  Stop.

Any suggestions?

**Comment by km4ack** [comment]
Which version of 73Linux are you running?

**Comment by jon-coffee** [comment]
Thanks for the reply Jason, looks like i'm running v 4.1.2

#######################################
#        Welcome to 73 Linux          #
#######################################
#############################
Checking for 73 Linux Updates
#############################
73 Linux up to date. Version 4.1.2 installed
Checking for updated bap files
bap files up to date

**Comment by km4ack** [comment]
That's the latest. I thought I had gotten rid of this bug in the last release. Can you try running two commands manually and see if you get any errors.
```
sudo apt update
sudo apt upgrade
```

**Comment by jon-coffee** [comment]
No errors that i can see when running update/upgrade. 

sudo apt update
Ign:1 http://packages.linuxmint.com wilma InRelease                            
Hit:2 http://archive.ubuntu.com/ubuntu noble InRelease                         
Hit:3 http://packages.linuxmint.com wilma Release                              
Get:4 http://security.ubuntu.com/ubuntu noble-security InRelease [126 kB]
Get:5 http://archive.ubuntu.com/ubuntu noble-updates InRelease [126 kB]
Get:7 http://archive.ubuntu.com/ubuntu noble-backports InRelease [126 kB]
Get:8 http://security.ubuntu.com/ubuntu noble-security/main amd64 Components [7,208 B]
Get:9 http://security.ubuntu.com/ubuntu noble-security/restricted amd64 Components [212 B]
Get:10 http://security.ubuntu.com/ubuntu noble-security/universe amd64 Components [51.9 kB]
Get:11 http://security.ubuntu.com/ubuntu noble-security/multiverse amd64 Components [212 B]
Get:12 http://archive.ubuntu.com/ubuntu noble-updates/main amd64 Components [114 kB]
Get:13 http://archive.ubuntu.com/ubuntu noble-updates/restricted amd64 Components [212 B]
Get:14 http://archive.ubuntu.com/ubuntu noble-updates/universe amd64 Components [305 kB]
Get:15 http://archive.ubuntu.com/ubuntu noble-updates/multiverse amd64 Components [940 B]
Get:16 http://archive.ubuntu.com/ubuntu noble-backports/main amd64 Components [208 B]
Get:17 http://archive.ubuntu.com/ubuntu noble-backports/restricted amd64 Components [212 B]
Get:18 http://archive.ubuntu.com/ubuntu noble-backports/universe amd64 Components [21.2 kB]
Get:19 http://archive.ubuntu.com/ubuntu noble-backports/multiverse amd64 Components [212 B]
Fetched 880 kB in 3s (319 kB/s)                                           
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
All packages are up to date.



sudo apt upgrade
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
Calculating upgrade... Done
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.

**Comment by km4ack** [comment]
Thanks for the results. No errors there. I'll take a look and see what I can figure out by doing a fresh build here.

**Comment by jon-coffee** [comment]
Much appreciated Jason!

**Comment by AE0SB** [comment]
Having the same problem here, fwiw. The entire FLsuite and WSJTX won't install using the script.

**Comment by km4ack** [comment]
Thanks for the report @AE0SB. I built a system this morning only installing the FL suite and wsjtx. All installed fine here. Going back to do a full build to see if I can reproduce the issue. In addition to you two guys here, I have had one other report yesterday of the same issue.

**Comment by km4ack** [comment]
this should be resolved in version 4.1.3
