### ISSUE TITLE
FLdigi doesn't install, wants PortAudio

### ISSUE THREAD

**Issue by dfreder1** [km4ack/73Linux#13]
me@Mintme:~/73Linux/cache/logs$ cat build-log.txt-Wed\ Dec\ 28\ 11\:20\:22\ AM\ PST\ 2022.txt | grep ' no'$

checking whether to enable maintainer-specific portions of Makefiles... no
checking whether we are cross compiling... no
checking minix/config.h usability... no
checking minix/config.h presence... no
checking for minix/config.h... no
checking dev/ppbus/ppi.h usability... no
checking dev/ppbus/ppi.h presence... no
checking for dev/ppbus/ppi.h... no
checking whether closedir returns void... no
checking whether gcc needs -traditional... no
checking for strlcpy... no
checking for CFPreferencesCopyAppValue... no
checking for CFLocaleCopyCurrent... no
checking for PORTAUDIO... no

**Comment by km4ack** [comment]
Which OS are you running. portaudio19-dev should be [installed as a dependency](https://github.com/km4ack/73Linux/blob/master/app/stable/x86_64/FLDIGI.bapp#L39) with FLDIGI.

**Comment by dfreder1** [comment]
$ cat /etc/os-release
NAME="Linux Mint"
VERSION="21 (Vanessa)"
ID=linuxmint
ID_LIKE="ubuntu debian"
PRETTY_NAME="Linux Mint 21"
VERSION_ID="21"
HOME_URL="https://www.linuxmint.com/"
SUPPORT_URL="https://forums.linuxmint.com/"
BUG_REPORT_URL="http://linuxmint-troubleshooting-guide.readthedocs.io/en/latest/"
PRIVACY_POLICY_URL="https://www.linuxmint.com/"
VERSION_CODENAME=vanessa
UBUNTU_CODENAME=jammy

**Comment by dfreder1** [comment]
$ cat /proc/version
Linux version 5.15.0-56-generic (buildd@lcy02-amd64-004) (gcc (Ubuntu 11.3.0-1ubuntu1~22.04) 11.3.0, GNU ld (GNU Binutils for Ubuntu) 2.38) #62-Ubuntu SMP Tue Nov 22 19:54:14 UTC 2022

**Comment by dfreder1** [comment]
$ dpkg -l | grep 'pulseaudio' && dpkg -l | grep 'portaudio'
ii  gir1.2-cvc-1.0                             5.4.2+vanessa                              amd64        Introspection data for Cinnamon pulseaudio abstraction
ii  gstreamer1.0-pulseaudio:amd64              1.20.3-0ubuntu1                            amd64        GStreamer plugin for PulseAudio (transitional package)
ii  libcvc-dbg:amd64                           5.4.2+vanessa                              amd64        Cinnamon pulseaudio abstraction library - debug symbols
ii  libcvc0:amd64                              5.4.2+vanessa                              amd64        Cinnamon pulseaudio abstraction library
ii  pulseaudio                                 1:15.99.1+dfsg1-1ubuntu2                   amd64        PulseAudio sound server
ii  pulseaudio-module-bluetooth                1:15.99.1+dfsg1-1ubuntu2                   amd64        Bluetooth module for PulseAudio sound server
ii  pulseaudio-utils                           1:15.99.1+dfsg1-1ubuntu2                   amd64        Command line tools for the PulseAudio sound server
ii  libportaudio2:amd64                        19.6.0-1.1                                 amd64        Portable audio I/O - shared library
ii  libportaudiocpp0:amd64                     19.6.0-1.1                                 amd64        Portable audio I/O C++ bindings - shared library

**Comment by dfreder1** [comment]
73Linux tries to install FLDigi v4.23, and even though I have the correct dependency installed (libportaudio2), the 73Linux log says PortAudio isn't installed. 

I Installed FLDigi outside the script with sudo apt install fldigi.

It installed v4.20 and it didn't install a new libportaudio2 version.

So...installing FLDigi with apt works fine, but doesn't with 73Linux, and it has something to do with libportaudio2.

Ah, linux.

**Comment by wf5w** [comment]
Just guessing here. But I am thinking that the build wants to see portaudio19-dev. Which is not installed by default on Linux Mint.

try doing sudo apt install portaudio19-dev

and see if you get any further.

Jerry WF5W

**Comment by km4ack** [comment]
This issue seems to be resolved. I just loaded FLDIGI on a new x86 build without issue.
