### ISSUE TITLE
Conky Preferences. Call Sign lookup

### ISSUE THREAD

**Issue by graycott** [km4ack/73Linux#15]
One thing  I started to like with the old  build a pi project  was the ability to change the  size and  call sign information within the conky display.  Another useful tool that was  in the  BAP was the call sign look up application. Is there a way of installing there two applications  into the 73 Linux system?

**Comment by km4ack** [comment]
The call sign lookup tool is still available to download and can be found [here](https://github.com/km4ack/pi-scripts/blob/master/getcall). 

Conky prefs is there but not fully tested. Run `~/bin/conky/./setconky`

**Comment by graycott** [comment]
Thank you Jason,
 the  conky edit  seem to work ok.  Another question is with the  Grid  Square information that was  used  in the  older version of Build a PI... I found that display within Conky was  useful to indicate that my GPS dongle  is running. This  also indicates  that my RTC was sync. to GPS time. Great to WSPR and  other time dependant modes.  Without that display I have to resort to running "CGPS" in terminal . IS it  possible to have the  GPS date reinstalled  in the Conky display?
Thank you
Graham 
VK4GRA

**Comment by km4ack** [comment]
Video coming soon to fix the GPS issue. Also working to update 73Linux to resolve this going forward.
