### ISSUE TITLE
Localisation Problem with conky

### ISSUE THREAD

**Issue by df6pa** [km4ack/73Linux#17]
Conky is looking for $HOME/documents/mylog.txt
If Linux Mint is installed with localisation the Documents folder might have another name e.g. Dokumente (german) and conky won't find mylog.txt and won't start

**Comment by df6pa** [comment]
I just added a link from Dokumente to Documents (ln -s Dokumente Documents) and did a touch mylog.txt in Dokumente and conky starts now

**Comment by km4ack** [comment]
Thanks for the report!
