### ISSUE TITLE
Conky shows no IP address in the NETWORK section

### ISSUE THREAD

**Issue by df6pa** [km4ack/73Linux#18]
Conky does not show the IP adddress because it is looking for wlan0, which is ok on the Raspberry PI, but the interface has a name like wlp2s0 or something like that under Mint. Just change that name in .conkyrc and it is ok.
73, Stephan

**Comment by km4ack** [comment]
Thanks! The fix is also [documented here](http://simp.ly/publish/3C9Zv0)
