### ISSUE TITLE
73Linux/x86LMint Update Issues

### ISSUE THREAD

**Issue by N1JCM** [km4ack/73Linux#20]
So, earlier I messaged about problems with getting the IC-705 to work with WSJT-X. The fix appeared to be to update WSJT-X to the latest revision, which uses an updated HAMLIB that does appear to support the IC-705. 

Unfortunately, noticing that I was unable to update WSJT-X (using the 73Linux update tool), I tried to update several other installed applications one at a time, including CHIRP, HAMLIB and FLRIG, without success. The update operation completed to the "REBOOT" dialog and upon reboot the requested application was not updated. There was no notice-able error presented in either the on-screen log or the stored on in ~/73linux/cache/logs, but no update.

Gateway x86-64 laptop with LMint installed under 73Linux; plenty of storage and memory.

Any thoughts?

Thanks,
--
Jeff Marden
N1JCM

**Comment by N1JCM** [comment]
No help, thanks anyway - Jeff Marden/N1JCM.

**Comment by km4ack** [comment]
Hamlib has been held at v4.4 as there were many reports of issues with 4.5. I'll have to take a look at Chirp and FLRIG when time permits.

**Comment by km4ack** [comment]
hamlib will update to the latest in the next release of 73Linux
