### ISSUE TITLE
RMS Express install option

### ISSUE THREAD

**Issue by neosentry** [km4ack/73Linux#22]
Has any consideration been given to adding RMS Express (formerly Winlink Express) via the wine facility already available in the 73Linux project toolkit?  I know running the big client on wine isn't as efficient as running PAT Winlink, especially on lightweight systems such as the Pi3B and Maestro Evolve III.. but for users of 73Linux that do have more horsepower available.. Pi4 (does requrie Box86), System76, etc., the option to use the RMS Express interface is a much prized thing.  ... and with the k6eta.org site being down, there are few avenues for many aspiring Linux-Ham Operators to travel. 73Linux could be a lifeline.

**Comment by neosentry** [comment]
Personally, I don’t care for Pat at all, as I’m just not a fan of unauthenticated email clients that interface via web ports.  It’s a pet peeve of mine.  I’ve tweaked it so Pat isn’t available on any IP other than the loopback.. and then I never allow it to remain open for more than a few minutes before shutting it down.. even when I’m fully remote and know that there are no clients on my walled garden network.. it’s still just something I don’t like.  I’m a much bigger fan of how RMS Express handles auto-form-fill templates and attachments. Pat has never impressed me there.  .. but.. that’s just me.  For those I’ve helped with RMS Ex on Wine? it’s really a matter getting just liking the client better than Pat.  Jim MARTIN - ***@***.*** Mar 20, 2023, at 18:09, KM4ACK ***@***.***> wrote:﻿
No plans to include Winlink Express at this time. I have update the link to the pdh.dll zip file for x86 users. Will have to wait on the version for the Pi as I don't maintain the script that installs VARA on the Pi.
Is there something that Winlink Express offers that you can't do in Pat?

**Comment by km4ack** [comment]
Fair enough. Locking it down to the loop back is a good security measure. Also, you can omit your password from the Pat config file and it will prompt you for it during the connection. 

Hopefully, the Winlink team will port it to be a native Linux app in the future. If you look at the very bottom of the [Winlink site](https://winlink.org/) on the left hand side, you will find they are looking for devs to implement it on other platforms. I would love to see it open sourced.
