### ISSUE TITLE
Uninstall 73 Linux?

### ISSUE THREAD

**Issue by tegwilym** [km4ack/73Linux#24]
Ok, kind of a bonehead mistake, but when running VNC to the Pi I guess I shouldn't be too embarrassed. 
I was installing 73 Linux on my Raspberry Pi4 which I was running VNC to.   I got my terminal windows backwards and accidentally installed on my main computer.  
Is there an easy way to remove most of the software?  I do already have some of the SDR programs installed but got my computers crossed and just wanted this on my Pi.
Thanks!
Tom KA7VIK

**Comment by km4ack** [comment]
Run 73Linux again and use the uninstall. Note this only works for certain apps and doesn't work on all of them at this time.
