### ISSUE TITLE
Flrig will not connect to 7300

### ISSUE THREAD

**Issue by Axtel4** [km4ack/73Linux#26]
I am setting up a new machine with Linux Mint 21.2 and 73Linux. When configuring Flrig, I get the following message:
Cannot open /dev/serial/by-id/usb-Silicon_Labs_CP2102_USB_to_UART_Bridge_Controll_IC-7300_02008737-if00-port0

After selecting the above USB device in the Configuration menu and clicking Init, I get the following message:
Transceiver not responding! - with a number of options to try.

I have double checked the Baud Rate, and other radio settings. I able to receive audio and correctly decode FT8 from the radio to Fldigi after manually setting the radio frequency and mode.

lsusb and dmesg shows the Silicon Labs device.

Flrig / Fldigi works correctly on my R-Pi 3 HamPi with the same radio settings.

I am at a loss as to what is keeping Flrig from connecting to the radio.

Thanks in advance.

**Comment by km4ack** [comment]
By chance did you install the GPS software? If so, run `cat /etc/default/gpsd
`and post the results.

**Comment by Axtel4** [comment]
No GPS. I have a minimum installation at this point,
Chirp,
Fldigi,
Flrig,
Flwrap,
Hamlib,
JS8, and
WSJTX.

Update and maybe a clue,
I tried CHIRP and received the following message:
[Errno 13] could not open port/dev/ttyS0:[Errno 13] Permission denied: 'dev/ttyS0'
