### ISSUE TITLE
Invalid desktop entry file: 'usr/local/share/applications/setconky.desktop'

### ISSUE THREAD

**Issue by hwdornbush** [km4ack/73Linux#27]
I just got a new Pi4 8GB and downloaded the Pi OS 64 bit, and installed it.  It booted just fine.  I then installed the latest 73Linux.  Based on recent experience firs downloading the 32-bit version and having trouble loading BAP, I started by just loading one app: Conky.  That seems to work although the Conky display is positioned so that my call sign its too high so that the top is cutoff.  Then I tried to run Hamradio > Conky Prefs
When I do this, I get a popup: Invalid desktop entry file: 'usr/local/share/applications/setconky.desktop'
There is no file usr/local/share/applications/setconky.desktop
Seems to be a bug in Conky Prefs.

**Comment by hwdornbush** [comment]
bash ~/bin/conky/setconky works.

**Comment by km4ack** [comment]
ok. that indicates an issue with the menu shortcut. thanks for testing it.

**Comment by km4ack** [comment]
When you have a second, run `cat ${HOME}/.local/share/applications/setconky.desktop` and post the results please.

**Comment by hwdornbush** [comment]
cat ${HOME}/.local/share/applications/setconky.desktop
cat: /home/pi/.local/share/applications/setconky.desktop: No such file or directory

**Comment by km4ack** [comment]
Tested on 32bit and the menu shortcut is ok. Testing on 64bit needed to see if I can reproduce the issue.

**Comment by km4ack** [comment]
Issue will be handled in #29

**Comment by hwdornbush** [comment]
I installed 73Linux 4.0.1 and I still get this error message.  I tried running bash ~/bin/conky/setconky

bash ~/bin/conky/setconky
/home/pi/bin/conky/laptop.86.86
cp: cannot stat '/home/pi/bin/conky/laptop.86.86': No such file or directory
conky: desktop window (c00171) is subwindow of root window (3a2)
conky: window type - normal
conky: drawing to created window (0x1600001)
conky: drawing to double buffer
conky: forked to background, pid is 2145

Still buggy

**Comment by km4ack** [comment]
On Pi 64bit?

**Comment by km4ack** [comment]
Created new [issue ticket](https://github.com/km4ack/73Linux/issues/36) to deal with this since it wasn't resolved in 4.0.1

**Comment by hwdornbush** [comment]
Yes, 64 bit
pi@Pi4-8:~ $ uname -a
Linux Pi4-8 6.1.21-v8+ #1642 SMP PREEMPT Mon Apr  3 17:24:16 BST 2023 aarch64 GNU/Linux
pi@Pi4-8:~ $ getconf LONG_BIT
64
