### ISSUE TITLE
Chirp bapp pulls wrong file for x86_64 systems

### ISSUE THREAD

**Issue by sdjrdriver** [km4ack/73Linux#3]
According to code

`        if [ `getconf LONG_BIT` = '32' ]; then

        LINK="https://github.com/goldstar611/chirp-appimage/releases/download/$CHIRPDATE/Chirp-daily-$CHIRPDATE-armhf.AppImage"

        else

        LINK="https://github.com/goldstar611/chirp-appimage/releases/download/$CHIRPDATE/Chirp-daily-$CHIRPDATE-aarch64.AppImage"

        fi

`
Neither of these packages will work for x86_64, which results in the following error during install/update

`chirp --version
bash: /usr/local/bin/chirp: cannot execute binary file: Exec format error`

Script should have 3rd possible for  Chirp-daily-#CHIRPDATE-x86_64.AppImage 

Hope this helps!

Computer is running Ubuntu 22.04 on an intel i7 processor

**Comment by km4ack** [comment]
look at the chirp.bapp file in /app/stable/x86_64/ The menu should have pulled this file instead

**Comment by sdjrdriver** [comment]
I have attached a copy of the install logs to show the behaviors during install
[log.zip](https://github.com/km4ack/73Linux/files/10080292/log.zip)

**Comment by sdjrdriver** [comment]
also appears that it is attempting to reference YAAC.bapp from the install as well.

`###################################
#Check Version  YAAC 	
###################################
/home/k5cdw/73Linux/app/stable/pi/YAAC.bapp: line 49: java: command not found
UPDATE: 180 is available and  is installed
###################################
`

**Comment by sdjrdriver** [comment]
Also there are more than a few of the bapp files that attempt to grab from the armhf branch which appears to be causing some minor issues

`k5cdw@wraithbox-linux:~/73Linux$ grep -rnw 'dpkg --add-architecture armhf' ./*
./app/stable/pi/HAMRS.bapp:34:			sudo dpkg --add-architecture armhf 
./app/stable/pi/PITERM.bapp:15:    sudo dpkg --add-architecture armhf
./app/stable/pi/ARDOP.bapp:18:		sudo dpkg --add-architecture armhf
./app/stable/pi/QTSOUND.bapp:15:    		sudo dpkg --add-architecture armhf
`
Might need some warning in the menus for these packages as they might fail to install or not install properly if the arch is set incorrectly.

**Comment by km4ack** [comment]
it looks like your architecture didn't get set. Do you have a cpu.bap file in the 73Linux/cache directory?

**Comment by sdjrdriver** [comment]
> it looks like your architecture didn't get set. Do you have a cpu.bap file in the 73Linux/cache directory?

No sir I do not, was that something the script was detecting and never set?

**Comment by km4ack** [comment]
Yes. Well, it should have. Delete everything in the cache directory and run the script again. This will simulate a first run. After the menu loads, select nothing and exit. Take a look at the cache folder again and see if that file is there.

**Comment by sdjrdriver** [comment]
Nope it misread lscpu output it looks like

`k5cdw@wraithbox-linux:~/73Linux$ ./73.sh 
#######################################
#        Welcome to 73 Linux          #
#######################################
#############################
Checking for 73 Linux Updates
#############################
73 Linux up to date. Version 4 installed
Checking for updated bap files
bap files up to date
#######################################
#  Updating repository & verifying    #
#  a few needed items needed before   #
#  we begin.                          #
#                                     #
#  Enter your sudo password if asked  #
#######################################
[sudo] password for k5cdw: 
Hit:1 http://us.archive.ubuntu.com/ubuntu jammy InRelease
Hit:2 https://download.docker.com/linux/ubuntu jammy InRelease                                                                                                                             
Hit:3 https://dl.winehq.org/wine-builds/ubuntu jammy InRelease                                                                                                                             
Hit:4 https://repo.steampowered.com/steam stable InRelease                                                                                                          
Hit:5 http://us.archive.ubuntu.com/ubuntu jammy-updates InRelease                                                                                            
Hit:6 https://packages.microsoft.com/repos/edge stable InRelease                                   
Hit:7 http://us.archive.ubuntu.com/ubuntu jammy-backports InRelease                                
Hit:8 http://security.ubuntu.com/ubuntu jammy-security InRelease
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
2 packages can be upgraded. Run 'apt list --upgradable' to see them.
./73.sh: line 150: [: =: unary operator expected
./73.sh: line 150: [: =: unary operator expected
###################################
#Registered  to this host
###################################
###################################
#Detected New System for Install
###################################
Hostname - wraithbox-linux
Probably Unsupported: ubuntu 22.04 you have a x86_64 with op-mode(s): cores

Community apps excluded
sed: can't read /home/k5cdw/73Linux/cache/cpu.bap: No such file or directory
sed: can't read /home/k5cdw/73Linux/cache/cpu.bap: No such file or directory
sed: can't read /home/k5cdw/73Linux/cache/cpu.bap: No such file or directory
sed: can't read /home/k5cdw/73Linux/cache/cpu.bap: No such file or directory
`

**Comment by km4ack** [comment]
Well that's not good. run the `lscpu` command and post the output. I'll have to look into this over the weekend after family leaves.

**Comment by sdjrdriver** [comment]
here's a bash -x for the part of the script in set-environment that i pulled out

`k5cdw@wraithbox-linux:~$ bash -x test.sh 
+ rm -f /tmp/bap-env-lscpu
+ lscpu
++ sed -n 's/^ID=/distribution=/p' /etc/os-release
+ eval distribution=ubuntu
++ distribution=ubuntu
++ sed -n 's/^VERSION_ID=/version=/p' /etc/os-release
++ tr -d '"'
+ eval version=22.04
++ version=22.04
++ cat /tmp/bap-env-lscpu
++ grep Architecture:
++ awk '{print $2}'
+ arch=x86_64
++ grep -m1 CPU /tmp/bap-env-lscpu
++ awk '{print $2}'
+ cpu='op-mode(s):'
`
with the following input from lscpu

`k5cdw@wraithbox-linux:~$ cat /tmp/bap-env-lscpu
Architecture:                    x86_64
CPU op-mode(s):                  32-bit, 64-bit
Address sizes:                   39 bits physical, 48 bits virtual
Byte Order:                      Little Endian
CPU(s):                          8
On-line CPU(s) list:             0-7
Vendor ID:                       GenuineIntel
Model name:                      Intel(R) Core(TM) i7-7700K CPU @ 4.20GHz
CPU family:                      6
Model:                           158
Thread(s) per core:              2
Core(s) per socket:              4
Socket(s):                       1
Stepping:                        9
CPU max MHz:                     4500.0000
CPU min MHz:                     800.0000
BogoMIPS:                        8400.00
Flags:                           fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush dts acpi mmx fxsr sse sse2 ss ht tm pbe syscall nx pdpe1gb rdtscp lm constant_tsc art arch_perfmon pebs bts rep_good nopl xtopology nonstop_tsc cpuid aperfmperf pni pclmulqdq dtes64 monitor ds_cpl vmx est tm2 ssse3 sdbg fma cx16 xtpr pdcm pcid sse4_1 sse4_2 x2apic movbe popcnt tsc_deadline_timer aes xsave avx f16c rdrand lahf_lm abm 3dnowprefetch cpuid_fault epb invpcid_single pti ssbd ibrs ibpb stibp tpr_shadow vnmi flexpriority ept vpid ept_ad fsgsbase tsc_adjust bmi1 avx2 smep bmi2 erms invpcid mpx rdseed adx smap clflushopt intel_pt xsaveopt xsavec xgetbv1 xsaves dtherm ida arat pln pts hwp hwp_notify hwp_act_window hwp_epp md_clear flush_l1d arch_capabilities
Virtualization:                  VT-x
L1d cache:                       128 KiB (4 instances)
L1i cache:                       128 KiB (4 instances)
L2 cache:                        1 MiB (4 instances)
L3 cache:                        8 MiB (1 instance)
NUMA node(s):                    1
NUMA node0 CPU(s):               0-7
Vulnerability Itlb multihit:     KVM: Mitigation: VMX disabled
Vulnerability L1tf:              Mitigation; PTE Inversion; VMX conditional cache flushes, SMT vulnerable
Vulnerability Mds:               Mitigation; Clear CPU buffers; SMT vulnerable
Vulnerability Meltdown:          Mitigation; PTI
Vulnerability Mmio stale data:   Mitigation; Clear CPU buffers; SMT vulnerable
Vulnerability Retbleed:          Mitigation; IBRS
Vulnerability Spec store bypass: Mitigation; Speculative Store Bypass disabled via prctl and seccomp
Vulnerability Spectre v1:        Mitigation; usercopy/swapgs barriers and __user pointer sanitization
Vulnerability Spectre v2:        Mitigation; IBRS, IBPB conditional, RSB filling, PBRSB-eIBRS Not affected
Vulnerability Srbds:             Mitigation; Microcode
Vulnerability Tsx async abort:   Mitigation; TSX disabled
`

**Comment by sdjrdriver** [comment]
Looks like looking for CPU in the eval might be problematic

**Comment by km4ack** [comment]
didn't solve the CPU eval yet but the revision i pushed should load the correct files. git pull for the latest or delete the 73Linux directory and do a new git clone. See if it will load the x86_64 files now.

**Comment by sdjrdriver** [comment]
Sure thing Jason. I'll do it tomorrow when I get home. I truly appreciate
all the effort you put into this. Have a good Thanksgiving man!

Charles Webb
K5CDW (Amateur Radio) / WRTH853 (GMRS)
Phone: 817-760-1356

**Comment by sdjrdriver** [comment]
Hey man,
Sorry it took so long to respond. Did a clean install and everything worked as expected!

Thanks for that. I will let you know if I run into anything else!
