### ISSUE TITLE
73Linux does not install ARDOP

### ISSUE THREAD

**Issue by AE0SB** [km4ack/73Linux#34]
I think the script still attempts to install the 'armhf' version of ARDOP, and that does not appear to work.

hardware: Lenovo Thinkpad T420
OS: Xubuntu 22.04

**Comment by km4ack** [comment]
It should be pulling ardopc64 with this [line of code](https://github.com/km4ack/73Linux/blob/master/app/stable/x86_64/ARDOP.bapp#L16). I wonder if the script misidentified your system? In your 73Linux/cache directory should be a cpu.bap file. Can you post the contents here please.

**Comment by km4ack** [comment]
I tested this morning on Mint 21.1 and it installed ardopc64 in /usr/local/bin/

**Comment by AE0SB** [comment]
```
64
4
x86_64
ubuntu
AE0SB
chris-T420
```

:shrug: I did edit ARDOP.bapp to say 

`    wget --tries 2 --connect-timeout=60 https://www.cantab.net/users/john.wiseman/Downloads/Beta/ardopc64
`

and it worked.
