### ISSUE TITLE
73 Linux install BETA software

### ISSUE THREAD

**Issue by kbmccroryva** [km4ack/73Linux#39]
I don't know whether this was on purpose or not but &# Linux installs a BETA version of WSJTX software rather than the current version that expired in 2024.  

This caused an issue with JS8CALL where wsjtx-data wasn't installed or found. I uninstalled WSJTX and installed the version provided by Linux Mint Software Manager. The update to js8call installed just fine. 

73
Kevin McCrory
WA4KBM

**Comment by KG4IIC** [comment]
73Linux installs WSJT-X 2.7.0-rc2.  By design it will be nonfunctional after Jan 15, 2024.  Please increase the priority on this issue.  Thanks and 73
