### ISSUE TITLE
Yikes!

### ISSUE THREAD

**Issue by edturk** [km4ack/73Linux#4]
Disaster install on Evolve III V1. 
Ran install script which finished with reboot request. After reboot lost my SD card and wireless card and system was very unstable.  tried to rerun 73 Linux but would not run again sent error msg in terminal window instead, which disappeared, I'll try to capture next time. Rebooted again and lost 73 Linux completely from menu, lost several other programs as well like Pat etc. Trying install script again to see if that cleans anything up

**Comment by km4ack** [comment]
Loss of the WiFi card will happen whenever the kernel is updated requiring a reinstall of the WiFi driver. This is a known issue with the Evolve laptops. If rerunning the script and re installing the WiFi driver doesn't clear it up, contact me through Patreon messaging.
