### ISSUE TITLE
Hangs on DIREWOLF_DEV

### ISSUE THREAD

**Issue by ke7uia** [km4ack/73Linux#43]
While running 73.sh on a new installation and an old installation: it appears to stop or hang at: 
###################################
#Check Version  DIREWOLF_DEV 	
###################################

Of course I wait 10 minutes or so and it continues, yet then reports the sudo password does not match. This is an indication that the timer turned off the sudo password.

**Comment by km4ack** [comment]
file will be removed on next update. not needed since 1.7 is stable now.
