### ISSUE TITLE
FLRIG not updating

### ISSUE THREAD

**Issue by km4ack** [km4ack/73Linux#44]
System is Mint 21.2
Ran 73 Linux to update FLDIGI from 4.1.27 to 4.2.0. Didn't see any error messages and install seemed successful but still running 4.1.27
Tried running 73 Linux twice but same result. Any suggestions? Thanks...

per this [forum post](https://groups.io/g/KM4ACK-Pi/message/11646)

**Comment by SpudGunMan** [comment]
is there a issue with a package? I just did a clean install on 21 and fldigi 4.2 was as expected

**Comment by km4ack** [comment]
Can't replicate. Upgraded from 4.1.27 to 4.2.02 without issue
