### ISSUE TITLE
LINBPQ does not install

### ISSUE THREAD

**Issue by arvdsar** [km4ack/73Linux#47]
LinBPQ doesn't install. There is a reference in the BPQ.bapp file referring to:
   source ${HOME}/pi-build/config || return

**Comment by roccoq** [comment]
BPQ sources a legacy config file from build-a-pi to get your call sign. Replace the line that sources the file with this:
```CALL=$(ls $HOME/73Linux/MYCALL.* | awk -F. '{print $2}')```
