### ISSUE TITLE
RPi5  install

### ISSUE THREAD

**Issue by peugenio** [km4ack/73Linux#49]
I just got my RPi5 and  I installed  64b Bookworm and is trying to install 73Linux.    I tried install all and it crashed so I am trying to install just a few items at a time.  I am getting the critical errors:

(yad:21918): Gdk-CRITICAL **: 19:52:52.997: gdk_x11_window_get_xid: assertion 'GDK_IS_X11_WINDOW (window)' failed

(yad:23784): Gdk-CRITICAL **: 19:53:02.156: gdk_x11_window_get_xid: assertion 'GDK_IS_X11_WINDOW (window)' failed

**Comment by SpudGunMan** [comment]
this is ignorable error
