### ISSUE TITLE
73Linux unistalls

### ISSUE THREAD

**Issue by husker73** [km4ack/73Linux#5]
ran script
73 linux installed and I only installed Conky just to try the interface out. 
I rebooted and ran HamRadio>73 Linux and asked if I wanted to update and click yes
It removed 73 linux from the menu structure.
I am running git script again to see if it fixes it. running on fresh install of mint on Fujitsu Laptop

**Comment by dfreder1** [comment]
Same here. Re-running git script fixed  it.  Evolve III Linux Mint.
