### ISSUE TITLE
libqt5multimedia5 missing in piqttermTCP

### ISSUE THREAD

**Issue by km4ack** [km4ack/73Linux#50]
Update for bookworm

sudo apt install libqt5multimedia5:armhf

**Comment by Hibby** [comment]
Hi there,

if it makes things easier, i run a repo over at https://online-amateur-radio-club-m0ouk.github.io/oarc-packages/ which maintains qttermtcp, qtsoundmodem & linbpq across raspbian 12, 11 arm64 and armhf, debian testing (13) and debian stable (12) amd64 and ubuntu jammy arm64 & amd64. It was initially intended for our uk packet radio network, but it makes sense for me to keep some backported packages for the wider radio community if it makes life easier as I've got all the infrastructure in place to maintain it!

I also maintain a lot of the amateur radio software in Debian which trickles down to ubuntu, raspbian, mint etc if you want some help getting some other things moving!  

Give me a shout here or over at hibby@debian.org :)
