### ISSUE TITLE
73Linux does not install pat 64-bit correctly

### ISSUE THREAD

**Issue by hwdornbush** [km4ack/73Linux#51]
I installed PI OS 64-bit legacy (Bullseye) using Raspberry Pi Imager.
I installed 73Linux using the command on this site.
I installed Pat and Pat Menu.
I got a warning that I needed to run Pat Configure to add my gridsquare.
When I tried
$ pat configure
I got 
pat: /lib/aarch64-linux-gnu/libc.so.6: version `GLIBC_2.32' not found (required by pat)
pat: /lib/aarch64-linux-gnu/libc.so.6: version `GLIBC_2.34' not found (required by pat)
I learned in https://groups.io/g/KM4ACK-Pi/topic/trying_to_get_pat_winlink/102688359 that this meant that some GLIBC files were missing.  I also learned that pat v0.12.1 worked.  I observed that the pat site began including 64-bit version starting with pat v0.13.0.
I downloaded the 32-bit version of pat 
pat_0.15.1_linux_armhf.deb
and double-clicked on it, and the installation occurred.  I ran 
$ pat configure
and now it worked, although the configuration file was missing what 73Linux or BAP inserted into it.  I copied the configuration file from a 32-bit BAP installation, to this 64-bit 73Linux system, and it worked.  Pat now loads and runs successfully.

My conclusion is that there is something amiss in the 64-bit installation that 73Linux attempts.

**Comment by km4ack** [comment]
Interesting. You are running Pi OS 64 bit (Bullseye) but downloaded Pat Winlink 32bit and it worked? Or am I misunderstanding something?

**Comment by km4ack** [comment]
Built 64bit Bullseye and got it up to date. Installed only Pat with 73. 73 does download the correct version (arm64.deb) and attempts the install. Like your example, it failed missing the same two dependencies. 

```
2023-11-29 12:45:25 (853 KB/s) - ‘pat_0.15.1_linux_arm64.deb’ saved [3222796/3222796]

Selecting previously unselected package pat.
(Reading database ... 157602 files and directories currently installed.)
Preparing to unpack .../pat_0.15.1_linux_arm64.deb ...
Unpacking pat (0.15.1) ...
Setting up pat (0.15.1) ...
Processing triggers for man-db (2.9.4-2) ...
pat: /lib/aarch64-linux-gnu/libc.so.6: version `GLIBC_2.32' not found (required by pat)
pat: /lib/aarch64-linux-gnu/libc.so.6: version `GLIBC_2.34' not found (required by pat)
```

**Comment by km4ack** [comment]
Mystery solved. Issue was with Pat Winlink. Pat Dev team has patched version available on GitHub. Just tested here and it works fine on Bullseye 64bit. See https://groups.google.com/g/pat-users/c/dawmYvN4DBc
