### ISSUE TITLE
setconky error when running on Pi

### ISSUE THREAD

**Issue by hwdornbush** [km4ack/73Linux#52]
When I run setconky (Start > Preferences > Conky_Prefs) using a Raspberry Pi, I cannot access the Pi large, medium, and small preferences.  I patched setconky to work with a Pi instead of x86, changing how it detects it is a Pi.

I renamed setconky to setconky.txt so I could upload it.

[setconky.txt](https://github.com/km4ack/73Linux/files/13490180/setconky.txt)

I removed the constant error messages after setconky runs by commenting several lines near the end of the script.  I have not seen any adverse effect from commenting those lines.

**Comment by km4ack** [comment]
Was this in Pi OS 64bit Bullseye?

**Comment by hwdornbush** [comment]
It happens in either Pi OS 32bit or 64bit Bullseye

**Comment by hwdornbush** [comment]
setconky uses 
CPU=$(lscpu | grep Architecture | grep arm)
but Architecture is set to aarch64
so I used Vendor ID: ARM 
I guess you could have also changed "grep arm" to "grep aarch64"

**Comment by km4ack** [comment]
Thank you for the additional info. Pushed fix to dev branch.
