### ISSUE TITLE
conky doesn't play nice with wayland

### ISSUE THREAD

**Issue by km4ack** [km4ack/73Linux#53]
Conky is unusable at this time if using Wayland.

**Comment by SpudGunMan** [comment]
for tracking https://github.com/brndnmtthws/conky/issues/56

**Comment by KB3LZV** [comment]
Conky is showing up in the middle of the screen and all black displaying no information that I can see

**Comment by mcangeli** [comment]
To use Conky on wayland, add these two lines on your Conky script.

conky.config = {
out_to_x = false,
out_to_wayland = true,

Change own_window_type to ‘override’ ( own_window_type = ‘override’,)

If you add these lines, Conky will works on Wayland without any issue. But Conky will not load on Xorg .

**Comment by Kb1hux** [comment]
Can someone tell me where this file is located please

**Comment by Kb1hux** [comment]
All the text is black. How do I correct this?

**Comment by NullVibes** [comment]
A work-around for Wayland is to open/save the `.conkyrc` file (no changes necessary.)  Conky will close itself, then re-open in the correct position.  Not a solution per se, but a band-aid that's working well for me.  I'll try that code-tweak, too, @mcangeli.

**Comment by NullVibes** [comment]
Added pull request #96 to test for Wayland, and add the appropriate Conky config lines.

**Comment by km4ack** [comment]
Thanks. I had a hunch that was the issue hence asking about the version of Ruby. Ran into that once before.

**Comment by NullVibes** [comment]
Which specific OS are you running?

**Comment by NullVibes** [comment]
Spinning up a fresh build now.  Will update when complete.

**Comment by kb8zgl** [comment]
Thank-you.  This was literally imaged and loaded yesterday 9/25/24.  I tried the work-around listed here and Conky just doesn’t start…. I’m trying to find if it is throwing an error.  Before the changes to the .conkyrc file here it started but all black on the right hand side.


From: NullVibes ***@***.***>
Date: Wednesday, September 25, 2024 at 5:06 PM
To: km4ack/73Linux ***@***.***>
Cc: kb8zgl ***@***.***>, Comment ***@***.***>
Subject: Re: [km4ack/73Linux] conky doesn't play nice with wayland (Issue #53)

Spinning up a fresh build now. Will update when complete.

**Comment by NullVibes** [comment]
UPDATES:

1 - Several errors are being observed during 73Linux build process under 32-bit Raspberry Pi OS (Bookworm) w/Desktop; dated 04JUL2024.  I'll have to re-run everything and kick output to a text file for review.  This *might* add significant time to reviewing this problem...

**Comment by G6BFP** [comment]
hi all so just loaded up to a pi 4 32 bit system conky and pota spots add on just a black square, tried to add the lines above file is lockedas read only,cant change permissions, getting a bit fed up, somone must have a working version of the config file, if so please share
