### ISSUE TITLE
TQSL on Rpi OS 12

### ISSUE THREAD

**Issue by ko4hxc** [km4ack/73Linux#56]
I am testing a fresh build on RPI OS  12 (bookworm) and 73linux

I followed all recommendations about new dependencies  

Still TQSL fails to build , error is attached

<img width="805" alt="Screen Shot 2023-12-23 at 12 04 11 PM" src="https://github.com/km4ack/73Linux/assets/80531630/0377b2ca-0873-44b4-aacf-c894b1e4b6aa">

Also as a note for the users of VARAC

Can I suggest adding by default the seguiemj.ttf file to windows/Fonts ?

KM4ACK you did a very good job with the new scripts

**Comment by km4ack** [comment]
This should be resolved in the dev branch of code. Still need to make a few more changes before pushing out as stable. Try building TQSL with the dev branch

**Comment by ko4hxc** [comment]
sudo I think i fixed it 
I needed to manually install sqllite3 and sqlite3-dev 

then I had to issue sudo ldconfig -v
cause tqsl wasnt resolving the shared library

Keep the hard work
73
Franco
KO4HXC

**Comment by km4ack** [comment]
Thanks for the report. I added your edits to the .bapp file in the dev branch. I'll test soon.
