### ISSUE TITLE
Ubuntu repository js8call has conflicts with files installed by 73Linux

### ISSUE THREAD

**Issue by dfrap** [km4ack/73Linux#57]
On Linux Mint js8call is marked for update as newer than the version installed by 73Linux.  The best resolution seems to be marking JS8call in Update Manager as Blocked package that will never receive updates.  Unfortunately, manual apt updates still try to update JS8call and cause problems.  

sudo apt upgrade
Calculating upgrade... Done
The following NEW packages will be installed:
  wsjtx-data
The following packages will be upgraded:
  js8call
Get:1 http://mirror.nodesdirect.com/ubuntu jammy/universe amd64 wsjtx-data all 2.5.4+repack-1 [3,684 kB]
Get:2 http://mirror.nodesdirect.com/ubuntu jammy/universe amd64 js8call amd64 2.2.0+ds-2 [4,793 kB]
Fetched 8,477 kB in 1s (8,526 kB/s)
(Reading database ... 691560 files and directories currently installed.)
Preparing to unpack .../wsjtx-data_2.5.4+repack-1_all.deb ...
Unpacking wsjtx-data (2.5.4+repack-1) ...
dpkg: error processing archive /var/cache/apt/archives/wsjtx-data_2.5.4+repack-1
_all.deb (--unpack):
 trying to overwrite '/usr/share/pixmaps/wsjtx_icon.png', which is also in packa
ge wsjtx 2.7.0-rc3
dpkg-deb: error: paste subprocess was killed by signal (Broken pipe)
Preparing to unpack .../js8call_2.2.0+ds-2_amd64.deb ...
Unpacking js8call (2.2.0+ds-2) over (2.2.0) ...
Errors were encountered while processing:
 /var/cache/apt/archives/wsjtx-data_2.5.4+repack-1_all.deb
E: Sub-process /usr/bin/dpkg returned an error code (1)
E: Unmet dependencies. Try 'apt --fix-broken install' with no packages (or specify a solution).
sudo apt install wsjtx-data
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
The following NEW packages will be installed:
  wsjtx-data
0 upgraded, 1 newly installed, 0 to remove and 0 not upgraded.
1 not fully installed or removed.
Need to get 0 B/3,684 kB of archives.
After this operation, 3,836 kB of additional disk space will be used.
(Reading database ... 691555 files and directories currently installed.)
Preparing to unpack .../wsjtx-data_2.5.4+repack-1_all.deb ...
Unpacking wsjtx-data (2.5.4+repack-1) ...
dpkg: error processing archive /var/cache/apt/archives/wsjtx-data_2.5.4+repack-1
_all.deb (--unpack):
 trying to overwrite '/usr/share/pixmaps/wsjtx_icon.png', which is also in packa
ge wsjtx 2.7.0-rc3
dpkg-deb: error: paste subprocess was killed by signal (Broken pipe)
Errors were encountered while processing:
 /var/cache/apt/archives/wsjtx-data_2.5.4+repack-1_all.deb
E: Sub-process /usr/bin/dpkg returned an error code (1)

My current ‘fix’:   sudo apt remove js8call

**Comment by bbc581** [comment]
+ 1 here as well

**Comment by km4ack** [comment]
resolved in 4.1.2
