### ISSUE TITLE
Conky doesnt display Network information

### ISSUE THREAD

**Issue by husker73** [km4ack/73Linux#6]
Conky doesn't display Network information

**Comment by km4ack** [comment]
I need to document this here as well but see [this page](https://app.simplenote.com/publish/3C9Zv0) for now.

**Comment by husker73** [comment]
That fixed the issue for wlan in conky.

73 NI0P
Brian

**Comment by Heartd0c** [comment]
Conky wasn’t looking right - got into conkyrc and discovered Gridsquare was commented out. Xgps shows good reception, so I’m not sure what’s going on. I un-commented that line and added a little voffset and now I show Gridsquare in white but no gridsquare value (in yellow). Not even NO GPS. Need help on this one.

Got Wireless IP to show up by changing wlan0 to wlo1 (ASUS E410MA). 

Definitely changed the minimum width to 400 (with max at 450) - display resolution is 1920x1080 - looks much better.

73, Jamie
WB4YDL

**Comment by km4ack** [comment]
Gridsqure in Conky isn't officially supported yet on x86 builds but will be coming in the near future. That is why it is commented out in the conkyrc file for now. Glad you got the ip addresses sorted out.
