### ISSUE TITLE
error with 73.sh when it checks wsjtx 

### ISSUE THREAD

**Issue by rtmpgh55** [km4ack/73Linux#61]
###################################
#Check Version  WSJTX 	
###################################
/home/pi/73Linux/bin/app-check.sh: line 48: ((: 1
1: syntax error in expression (error token is "1")
sed: -e expression #1, char 18: unterminated `s' command

CRITICAL: parsing error on .bapp /home/pi/73Linux/app/stable/pi/WSJTX.bapp
###################################

**Comment by km4ack** [comment]
Another user has reported this same issue. Need to look at this again.

**Comment by amelluk** [comment]
Same issue here. 
Pi 5 Bookworm Linux raspberrypi9 6.6.28+rpt-rpi-2712 #1 SMP PREEMPT Debian 1:6.6.28-1+rpt1 (2024-04-22) aarch64 GNU/Linux

**Comment by kuperman** [comment]
Issue is that with a release candidate, the curl call is returning two versions of the software.

```
wsjtx_2.6.1_arm64.deb
wsjtx-2.7.0-rc4_arm64.deb
```

And the earlier fix https://github.com/km4ack/73Linux/commit/bc290811ac37a038467e03cff7556c4e8aa9728c is taking the second of the two options.

However, the code to clean up the first part of the file name is only trimming prefix with an underscore, but the second one uses a dash instead. If you want to remove either with a `-` or `_` then `sed 's/wsjtx[-_]//'` should handle either case. Then you can decide if you want the first one (stable) or last one (most recent) and use head or tail as desired.

It'll be a bit before I can put together a PR with the fix.
