### ISSUE TITLE
CONKY install issue possibly 

### ISSUE THREAD

**Issue by rtmpgh** [km4ack/73Linux#63]
while installing a Pi4
I got this error not sure if it installed or not due to scroll back limits I forgot to change

E: Unable to locate package ruby2.7
E: Couldn't find any package by glob 'ruby2.7'
E: Couldn't find any package by regex 'ruby2.7'

**Comment by km4ack** [comment]
Needs to be updated to ruby3.0

**Comment by km4ack** [comment]
This should be resolve in PR #95
