### ISSUE TITLE
Should I be seeing a Grid Square displayed in Conky?

### ISSUE THREAD

**Issue by BobSegrest** [km4ack/73Linux#7]
I have installed the latest 73Linux distribution with all options selected on an x86 laptop running Mint Cinnamon.  I have a USB GPS device connected and configured.  XGPS is working.  I am not seeing a grid square displayed in CONKY.  Did I miss something?

Bob, KO2F

**Comment by km4ack** [comment]
Currently this feature hasn't been fully tested so it was commented out in the conkyrc file for the time being. Feel free to play with it by uncommenting it.
