### ISSUE TITLE
Problem loading page in Firefox for Pat Winlink

### ISSUE THREAD

**Issue by gil2git** [km4ack/73Linux#76]
When I start up any  of the modems  in Pat Winlink,  the 127.0.0.1:8080 page has a problem loading in Firefox.  Details say the connection to the site is not private.  Using 73Linux on Linux Mint.

**Comment by km4ack** [comment]
Pat uses http instead of https with Pat so this isn't surprising. You might see if there's an open issue with the Pat team https://github.com/la5nta/pat
