### ISSUE TITLE
Add DNS-SD to Direwolf install script

### ISSUE THREAD

**Issue by mmirabent** [km4ack/73Linux#81]
I've submitted a PR to add the `ibavahi-client-dev` libraries before building Direwolf.

Direwolf 1.7 adds the ability for Direwolf to advertise itself as a KISS TNC via DNS Service Discovery. This allows it to be auto discovered by apps like Radiomail on iOS. I've tested this on my Raspberry Pi 4 running Bullseye. I'm currently rebuilding to test on Bookworm as well.

I wasn't sure if you accepted PRs or what the etiquette was for submitting them but here's my contribution

Reference:
* https://github.com/wb2osz/direwolf/releases/tag/1.7
* https://github.com/dcasati/direwolf-kiss-wifi

#80

**Comment by km4ack** [comment]
I'll be happy to grab the PR for the next release. My only request is that you make the PR against the dev branch. Thanks for the contribution!!

**Comment by mmirabent** [comment]
Rebased to dev

**Comment by km4ack** [comment]
https://github.com/km4ack/73Linux/pull/80 merged into dev branch.
