### ISSUE TITLE
Recent install of 73Linux on Evolve - Patmenu won't update with 73 Linux from DEV

### ISSUE THREAD

**Issue by KD7UM** [km4ack/73Linux#83]
I recently rebuilt my Evolve laptops and ran 73Linux from the Github link.  After the reboot following the initial install of the apps I ran it again to update the apps.  Patmenu was listed as DEV with 2.12 available.  Tried updating Patmenu and it stayed at DEV level.

The Dev level has lots of bugs including no way to find Packet gateways and create alias for them.  The header on the YAD menu says ARDOP and only allows ARDOP and VARA HF.

Thanks

**Comment by km4ack** [comment]
DEV is the latest version for x86 platform as of July 2024. Specific bugs for pat menu should be reported at https://github.com/km4ack/patmenu2/issues
