### ISSUE TITLE
Unable to start build on Linux Mint 19.3 Tricia 32 bit - no apps available to select for build

### ISSUE THREAD

**Issue by igorshalar** [km4ack/73Linux#89]
I've started the 73.sh script and clicked [Select Apps for build] at the first window. When the second window appeared no apps are displayed in it. 
Please help resolve the issue. 
![Screenshot at 2024-07-15 17-37-23](https://github.com/user-attachments/assets/ba123bad-2d67-4114-b5c9-c78729085785)

System info:
![Screenshot at 2024-07-15 17-35-33](https://github.com/user-attachments/assets/e41bfbd7-9e69-4866-9fd0-e3d4e71e3aac)

Terminal log:
```
➜  73Linux git:(master) ✗ bash $HOME/73Linux/73.sh
#######################################
#        Welcome to 73 Linux          #
#######################################
#############################
Checking for 73 Linux Updates
#############################
73 Linux up to date. Version 4.0.5 installed
Checking for updated bap files
bap files up to date
#######################################
#  Updating repository & verifying    #
#  a few needed items needed before   #
#  we begin.                          #
#                                     #
#  Enter your sudo password if asked  #
#######################################
Hit:1 http://mirror.arizona.edu/ubuntu bionic InRelease
Ign:2 http://packages.linuxmint.com tricia InRelease                                                                                           
Hit:3 http://mirror.arizona.edu/ubuntu bionic-updates InRelease                                                                                
Hit:4 http://packages.linuxmint.com tricia Release                                                                                             
Hit:5 http://archive.canonical.com/ubuntu bionic InRelease                                                                                     
Hit:6 http://mirror.arizona.edu/ubuntu bionic-backports InRelease                                                   
Hit:7 http://ppa.launchpad.net/gpredict-team/ppa/ubuntu bionic InRelease                      
Hit:8 http://security.ubuntu.com/ubuntu bionic-security InRelease       
Reading package lists... Done                     
Building dependency tree       
Reading state information... Done
All packages are up to date.
Loading build script
Community apps excluded
###################################
# Verifying .bapp Plug-Ins 
###################################
###################################
# Scanning .bapp Plug-Ins 
###################################
/home/zeon/73Linux/bin/app-check.sh: line 38: [: too many arguments
head: error reading 'app': Is a directory
/home/zeon/73Linux/bin/app-check.sh: line 38: [: ==: unary operator expected
head: error reading 'bin': Is a directory
/home/zeon/73Linux/bin/app-check.sh: line 38: [: ==: unary operator expected
head: error reading 'cache': Is a directory
/home/zeon/73Linux/bin/app-check.sh: line 38: [: ==: unary operator expected
head: error reading 'data': Is a directory
/home/zeon/73Linux/bin/app-check.sh: line 38: [: ==: unary operator expected
/home/zeon/73Linux/bin/app-check.sh: line 38: [: ==: unary operator expected
/home/zeon/73Linux/bin/app-check.sh: line 38: [: too many arguments
###################################
#      Welcome KN6ZEO 	
###################################
```

**Comment by km4ack** [comment]
We have seen this previously when the language is set to German. If you have it set to German, try setting the language to English and it should display the apps.

**Comment by igorshalar** [comment]
> We have seen this previously when the language is set to German. If you have it set to German, try setting the language to English and it should display the apps.

Hi Jason, if you mean the system language, I haven't changed it and it is set to English.

**Comment by NullVibes** [comment]
@igorshalar
Looks like an issue with the Bash If/Then statement in app-check.sh script, line 38:
`if [ $CHECKFILE == $CURBAPVER ];then`

Could be that version of Bash being fickle...

Modify that line (38) to read:
`if [[ $CHECKFILE == $CURBAPVER ]]; then`

Let us know if that works...

**Comment by igorshalar** [comment]
> @igorshalar Looks like an issue with the Bash If/Then statement in app-check.sh script, line 38: `if [ $CHECKFILE == $CURBAPVER ];then`
> 
> Could be that version of Bash being fickle...
> 
> Modify that line (38) to read: `if [[ $CHECKFILE == $CURBAPVER ]]; then`
> 
> Let us know if that works...

Hey NullVibes, thanks for the help. I've updated the script with your suggestion, but now I am getting other errors:
```
###################################
# Scanning .bapp Plug-Ins 
###################################
head: error reading 'app': Is a directory
head: error reading 'bin': Is a directory
head: error reading 'cache': Is a directory
head: error reading 'data': Is a directory
###################################
```
How can I fix this?

**Comment by JerryKd0uxw** [comment]
I am encountering the same issue.  Have altered line 38 in app-check.sh and now seeing same result as @igorshalar from Aug 7th.  Using 32 bit Bullseye on a Raspberry Pi 3B Plus Rev 1.2

**Comment by JerryKd0uxw** [comment]
I have resolved my issue (as far as getting 73.sh to run to completion without errors generated). It appears that global variable APPSFILES (set in 73.sh) is not being passed to the other scripts. Since I'm using this with a pi, I declared it in app-check.sh and again in menu.sh.  This has allowed the scripts to run.  However, none of the selected apps were installed.  Somewhere else I need to add this?
![73Linux](https://github.com/user-attachments/assets/af854fbf-58fa-4b95-aa43-eae8f9418a6b)

**Comment by JerryKd0uxw** [comment]
Needed to do runner.sh as well.  After these modifications the build went fine (slow, but fine).
![image](https://github.com/user-attachments/assets/a6bfc7dd-3131-4266-ae0b-e7cb16adb94c)

**Comment by igorshalar** [comment]
@JerryKd0uxw thanks for sharing. I'll try your steps.

**Comment by km4ack** [comment]
Looks like this issue is resolved even though 73Linux doesn't officially support Mint 19
