### ISSUE TITLE
CHIRP.AppImage broken upstream

### ISSUE THREAD

**Issue by NullVibes** [km4ack/73Linux#91]
--- For documentation purposes ---
CHIRP.AppImage seems to be broken due to an ongoing issue upstream.
[https://github.com/goldstar611/chirp-appimage/issues/9]  

When the list of apps is built, an error dump can be observed in the terminal, ending with:
> ...
> pkg_resources.DistributionNotFound: The 'suds' distribution was not found and is required by chirp

Installing the `python3-suds` package does *not* solve this issue.
The CHIRP application icon is still displayed in the menu, but is not functional.

**Comment by goldstar611** [comment]
Hi @km4ack @NullVibes,

I intend to take a look at this issue soon. My main development machine power supply (which is a proprietary form-factor unfortunately) has failed which has prevented me from being more responsive.

**Comment by NullVibes** [comment]
Looks like the issue has been resolved.  Tested on Mint 22.
