### ISSUE TITLE
Update ARDOPC 

### ISSUE THREAD

**Issue by km4ack** [km4ack/73Linux#93]
https://github.com/Dinsmoor/ardopcf/blob/master/README.md

**Comment by kd2var** [comment]
Is conkyrc and start ARDOP modem in pat menu updated to look for ardor instead of ardoc64? I had to make those changes to get everything to work correctly when I installed ardopcf a few weeks ago.

**Comment by km4ack** [comment]
I didn't even think about it at the time but have created the following issue tickets:
https://github.com/km4ack/73Linux/issues/101
https://github.com/km4ack/patmenu2/issues/92
