### ISSUE TITLE
Conky Blank Gridsquare Condition Due to Missing Ruby Gems

### ISSUE THREAD

**Issue by NullVibes** [km4ack/73Linux#94]
The `gpsd_client` and `maidenhead` Ruby gems are **not** installed during the initial build.  This causes the `$HOME/bin/conky/get-grid` bash script to quietly fail, the `/run/user/$UUID/gridinfo.txt` is overwritten with no data, then creates a condition where a blank Gridsquare is displayed in Conky, even if a 3D fix can be observed with a gpsd client such as cgps.

**Installing the necessary Ruby gems fixes this issue.**
`sudo gem install gpsd_client maidenhead`

**Comment by km4ack** [comment]
Both of those are set to be installed by these lines of code https://github.com/km4ack/73Linux/blob/master/app/stable/x86_64/CONKY.bapp#L27-L29 Not sure why they weren't installed on your system.

**Comment by km4ack** [comment]
Which platform and OS did this occur?

**Comment by NullVibes** [comment]
Raspberry Pi running Bookworm 64-bit

**Comment by km4ack** [comment]
Just out of curiosity, which version of Ruby is installed?

The code I sent before was for x86 but the same thing is [coded](https://github.com/km4ack/73Linux/blob/master/app/stable/pi/CONKY.bapp#L15-L17) for the Pi.

**Comment by NullVibes** [comment]
Figured it out...  Ruby version 2.7 is no longer in the repos, so that install fails, then causes the gem install to fail.  Pull request #95 submitted.
